const githubApi = {
  login: "aogles",
  id: 119542673,
  node_id: "U_kgDOByATkQ",
  avatar_url: "https://avatars.githubusercontent.com/u/119542673?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/aogles",
  html_url: "https://github.com/aogles",
  followers_url: "https://api.github.com/users/aogles/followers",
  following_url: "https://api.github.com/users/aogles/following{/other_user}",
  gists_url: "https://api.github.com/users/aogles/gists{/gist_id}",
  starred_url: "https://api.github.com/users/aogles/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/aogles/subscriptions",
  organizations_url: "https://api.github.com/users/aogles/orgs",
  repos_url: "https://api.github.com/users/aogles/repos",
  events_url: "https://api.github.com/users/aogles/events{/privacy}",
  received_events_url: "https://api.github.com/users/aogles/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2022-11-30T22:14:02Z",
  updated_at: "2023-01-04T17:23:48Z",
};
export default githubApi;
